[package]
name = "smiles-parsing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
molrs = "0.1.1"
pertable = "0.1.4"
